"""empty message

Revision ID: 94263388ece9
Revises: 
Create Date: 2024-10-02 10:55:20.456494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94263388ece9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
